(define balance 100)

(define (withdraw amount)
  (if (>= balance amount)
      (begin (set! balance (- balance amount))
	     balance)
      "Insufficient funds"))

(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
	(begin (set! balance (- balance amount))
	       balance)
	"Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
	  ((eq? m 'deposit) deposit)
	  (else (error "Unknown request -- MAKE-ACCOUNT" m))))
  dispatch)

;problem 3-1
(define (make-accumulator ac)
  (define (accumulator amount)
    (begin (set! ac (+ ac amount))
	   ac))
  accumulator)

; problem 3-2
(define (make-monitored f)
  (define manycalls 0)
  (define (dispatch m)
    (cond ((eq? m 'how-many-calls?) manycalls)
	  (else (begin (set! manycalls (+ manycalls 1))
		       (f m)))))
  dispatch)
